# Generated by Django 4.0.4 on 2022-05-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userregistration_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
